<a href="https://colab.research.google.com/github/prikshit-2000/Transformers-NLP/blob/main/Transformers_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch
!pip install transformers

# ***Pytorch***

In [3]:
import torch
from transformers import AutoModel,BertConfig,BertModel

In [6]:
config = BertConfig()
model = BertModel(config)
print(config)

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.8.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



In [7]:
model = BertModel.from_pretrained('bert-base-cased')

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [8]:
model.save_pretrained('berty-boy')

In [11]:
sequences = [
  "Hello!",
  "Cool.",
  "Nice!"
]

In [12]:
encoded_sequences = [
  [ 101, 7592,  999,  102],
  [ 101, 4658, 1012,  102],
  [ 101, 3835,  999,  102]
]

In [13]:
model_inputs = torch.tensor(encoded_sequences)
outputs = model(model_inputs)

In [14]:
outputs

BaseModelOutputWithPoolingAndCrossAttentions([('last_hidden_state',
                                               tensor([[[ 4.4496e-01,  4.8276e-01,  2.7797e-01,  ..., -5.4033e-02,
                                                          3.9394e-01, -9.4770e-02],
                                                        [ 2.4943e-01, -4.4093e-01,  8.1772e-01,  ..., -3.1917e-01,
                                                          2.2992e-01, -4.1172e-02],
                                                        [ 1.3668e-01,  2.2518e-01,  1.4502e-01,  ..., -4.6915e-02,
                                                          2.8224e-01,  7.5566e-02],
                                                        [ 1.1789e+00,  1.6739e-01, -1.8187e-01,  ...,  2.4671e-01,
                                                          1.0441e+00, -6.1963e-03]],
                                               
                                                       [[ 3.6436e-01,  3.2465e-02,  2.0

# ***Tensorflow***

In [15]:
import tensorflow as tf


In [16]:
from transformers import BertConfig,TFBertModel
config = BertConfig()
model = TFBertModel(config)

In [18]:
config

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.8.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

In [26]:
model = TFBertModel.from_pretrained('bert-base-cased')

Some layers from the model checkpoint at bert-base-cased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [27]:
model.save_pretrained('berty-boy-tf')

In [28]:
sequences = [
  "Hello!",
  "Cool.",
  "Nice!"
]

In [29]:
encoded_sequences = [
  [ 101, 7592,  999,  102],
  [ 101, 4658, 1012,  102],
  [ 101, 3835,  999,  102]
]

In [30]:
model_inputs = tf.constant(encoded_sequences)
outputs = model(model_inputs)

In [31]:
outputs

TFBaseModelOutputWithPooling([('last_hidden_state',
                               <tf.Tensor: shape=(3, 4, 768), dtype=float32, numpy=
                               array([[[ 4.4495681e-01,  4.8276228e-01,  2.7797207e-01, ...,
                                        -5.4032493e-02,  3.9393464e-01, -9.4769925e-02],
                                       [ 2.4942891e-01, -4.4092980e-01,  8.1772327e-01, ...,
                                        -3.1916553e-01,  2.2992226e-01, -4.1171759e-02],
                                       [ 1.3667528e-01,  2.2517809e-01,  1.4502001e-01, ...,
                                        -4.6914704e-02,  2.8224200e-01,  7.5565502e-02],
                                       [ 1.1788851e+00,  1.6738476e-01, -1.8187092e-01, ...,
                                         2.4671432e-01,  1.0440764e+00, -6.1964244e-03]],
                               
                                      [[ 3.6435851e-01,  3.2464251e-02,  2.0257653e-01, ...,
          